name: Check Old PRs and Notify Slack

on:
  schedule:
    - cron: "0 9 * * 1-5"
  workflow_dispatch:

jobs:
  notify-old-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Watchdog Repository
        uses: actions/checkout@v2
        with:
          repository: akhilesh-s/watchdog
          path: watchdog

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd watchdog
          npm install

      - name: Execute Script
        run: |
          cd watchdog
          node src/index.js
        env:
          OWNER: "akhilesh-s"
          REPO: "[vid-box, notes-nest-client, watchdog]"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # generate webhook url for a specific channel
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # generate github token (PAT)
          GITHUB_TO_SLACK_MAP: |
            akiresu-sama: U07F9A80URY
            Harkarman: D07FND7QWUA
            aadilterngroup: D07HUS72N0J
            akshayrao14: D07FG4D2Q4S
            hritik-tern: D07FGDE5751
            rahul-kamboj-tern: D07FL772E92
            shadab-tern: D07FG9HQCHY
            ShrutiKhatri826: D07FJMJBPRS
            vaibhavp-tern: D07KPCELHLN
            Yogesh-K-Tern: D07KT5A5P6Z
